### PR TITLE
Update to the latest easyRSA version.

### PR DESCRIPTION
**Pull request by uubk**
Also add support for kerberos certificate types.

### CODE REVIEW

**Comment by uubk** [comment]
@ThreeFx @F1rst-Unicorn I've tested this one with both existing and new CA's, but since a lot of stuff blows up if this breaks and I changed the EasyRSA version - do you also want to give this a test drive?

**Comment by ThreeFx** [comment]
I will test this at home in the coming days.

**Comment by ThreeFx** [comment]
Nothing bad happened for me - all seems to work fine.

Doesn't this only affect new CAs though? I didn't delete and reissue the certs at home.

**Comment by uubk** [comment]
Yes, it _should_ only affect new CAs (which is also tested in CI), in that case, I'll merge it.

**Pull request merged**
